name: Terraform Workflow on Feature Branch

on:
  push:
    branches:
      - feature/*

jobs:
  fmt-validate:
    name: Format And validate
    runs-on: ubuntu-latest
    env:
      APP_AUTO_TFVARS: config.dev.tfvars
 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run terraform fmt check
        run: |
          terraform init -backend-config=${{env.APP_AUTO_TFVARS}} -migrate-state
          terraform fmt -check -diff
          terraform validate
  scan-security:
    name: tfsec sarif report
    runs-on: ubuntu-latest
    env:
      APP_AUTO_TFVARS: config.dev.tfvars

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        run: terraform init -backend-config=${{env.APP_AUTO_TFVARS}}
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          format: sarif
          soft_fail: false
          additional_args: --out result.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: result.sarif

      - name: Comments On Pull Request
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [ fmt-validate, scan-security]
    env: 
      APP_AUTO_TFVARS: config.dev.tfvars
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@625cb76050397c6b3a1789261eb129f8f39a206b
        with:
          terraform_version: ${{ inputs.version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=${{env.APP_AUTO_TFVARS}}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
 
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    steps:
      - run: echo "Pruebas unitarias sobre el codigo"
